{% set version = "20210214" %}
{% set name = "sagemath-db-graphs" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://users.ox.ac.uk/~coml0531/sage/graphs-{{ version }}.tar.bz2
  sha256: 07237c0d9853611505c389fd7bb92500c8743f5631babb4d0f45dfd8332f3741

build:
  number: 0
  noarch: generic

test:
  commands:
    - test -f "$PREFIX/share/graphs/graphs.db"

about:
  home: https://github.com/sagemath/sage
  license: GPL-2.0-or-later
  summary: |
    A database of graphs. Created by Emily Kirkman based on the work of Jason
    Grout. Since April 2012 it also contains the ISGCI graph database.

extra:
  recipe-maintainers:
    - isuruf
